name: asset_ledger
description: "机账通：面向工程机械经营场景的记录与管理工具。"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理
  provider: ^6.1.2

  # DB
  sqflite: ^2.3.3+1

  # 路径工具
  path: ^1.9.0

  # ✅ Step 10-6 需要：获取 App 私有目录（保存头像）
  path_provider: ^2.1.4

  # ✅ Step 10-6 需要：选择相册/拍照获取头像图片
  image_picker: ^1.1.2
  in_app_review: ^2.0.10
  url_launcher: ^6.3.1

  # iOS 风格图标
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.4+4
  custom_lint: ^0.8.1
  asset_ledger_architecture_lints:
    path: tools/asset_ledger_architecture_lints
  patrol: ^4.1.1

flutter:
  uses-material-design: true

  # ✅ 品牌头像 assets
  assets:
    - assets/brands/
    - assets/navigation/
    - assets/images/

patrol:
  test_directory: integration_test
